# Generated by Django 5.2.4 on 2025-08-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='Mission')),
                ('titre', models.CharField(max_length=255)),
                ('prix', models.CharField(max_length=255)),
                ('date', models.DateTimeField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
