# Generated by Django 5.2.5 on 2025-08-18 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('accepte', 'Accepté'), ('refuse', 'Refusé'), ('en_attente', 'En attente'), ('termine', 'Terminé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='Categorie')),
                ('titre', models.CharField(max_length=255)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='backend.mission')),
            ],
        ),
    ]
