# Generated by Django 5.2.5 on 2025-08-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_mission_created_by_mission_status_alter_mission_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='mission',
        ),
        migrations.AddField(
            model_name='mission',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='missions', to='backend.categorie'),
        ),
    ]
