# Generated by Django 5.1.3 on 2025-08-19 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_categorie_mission_mission_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='photo',
            field=models.ImageField(upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mission',
            name='image',
            field=models.ImageField(upload_to='missions/'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
